version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: journal_telegram_bot
    restart: always
    environment:
      - PYTHONUNBUFFERED=1  # Ensure real-time logging
      - .env
    volumes:
      - .:/app  # Sync local files with container for easier debugging
    command: python app.py  # Start the bot with polling

# Optional network configuration (if needed)
networks:
  default:
    driver: bridge
